// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKxiuSUK5ePoKQVzIiS3P3fyZlUIusR9c',
    appId: '1:164456287439:web:d483a68d55afc4cb50fbba',
    messagingSenderId: '164456287439',
    projectId: 'smartpickup-28fe0',
    authDomain: 'smartpickup-28fe0.firebaseapp.com',
    storageBucket: 'smartpickup-28fe0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzHfFurdR0BW0L-enWf3mj5yz9kW9uD3I',
    appId: '1:164456287439:android:96e3af2204506bb050fbba',
    messagingSenderId: '164456287439',
    projectId: 'smartpickup-28fe0',
    storageBucket: 'smartpickup-28fe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0utGYhEw1BaPl1AidpdvM0KyL_Y1zeBo',
    appId: '1:164456287439:ios:d02e120c37de132950fbba',
    messagingSenderId: '164456287439',
    projectId: 'smartpickup-28fe0',
    storageBucket: 'smartpickup-28fe0.firebasestorage.app',
    iosBundleId: 'com.example.smartpickup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0utGYhEw1BaPl1AidpdvM0KyL_Y1zeBo',
    appId: '1:164456287439:ios:d02e120c37de132950fbba',
    messagingSenderId: '164456287439',
    projectId: 'smartpickup-28fe0',
    storageBucket: 'smartpickup-28fe0.firebasestorage.app',
    iosBundleId: 'com.example.smartpickup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKxiuSUK5ePoKQVzIiS3P3fyZlUIusR9c',
    appId: '1:164456287439:web:05a1f5e409bb367a50fbba',
    messagingSenderId: '164456287439',
    projectId: 'smartpickup-28fe0',
    authDomain: 'smartpickup-28fe0.firebaseapp.com',
    storageBucket: 'smartpickup-28fe0.firebasestorage.app',
  );

}